### ISSUE TITLE
Leftovers and Browser Testing

### ISSUE THREAD

**Issue by cathywilkie** [cathywilkie/ecommerce-pattern-library#3]
Hi Thomas!
I finished the leftovers and Browser testing (checking all the boxes!)
However, I tried to start creating my starter product list page, and the 'Preparing product data', and I feel like I broke everything...
I also realized my icons and Logo colour would reset (to black instead of white) everytime I close and open Jekyll in the Terminal. Any idea why or how I can fix that?

@thomasjbradley

**Comment by thomasjbradley** [comment]
Product page: seems to be a typo in your `_config.yml` The indentation on these lines is all wonky.
https://github.com/cathywilkie/ecommerce-pattern-library/blob/master/_config.yml#L26-L33

Paste this instead:

```yml
collections:
  products:
    output: true
defaults:
  - scope:
      path: _products
    values:
      layout: product
```

Image resetting: are you making adjustments inside the `_site` folder? That folder is deleted and recreated by Jekyll regularly.
